CREATE TABLE Contacted (
USER_ID varchar(17) NOT NULL,
CONTACT_DT datetime NOT NULL,
CONTACT_USER_ID varchar(17) NOT NULL,
EXPOSE_NOTIFY boolean NOT NULL,
PRIMARY KEY (USER_ID, CONTACT_DT, CONTACT_USER_ID));


CREATE TABLE Exposed (
USER_ID varchar(17) NOT NULL,
EXPOSE_DT datetime NOT NULL,
PRIMARY KEY (USER_ID, EXPOSE_DT),
UNIQUE KEY (USER_ID));
